name: flutter_ai_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  intl: ^0.18.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  fake_cloud_firestore: ^2.3.0+3
  
flutter:
  uses-material-design: true