// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBqNyjRUoGA52_opdHR-oN-JdBBJc5Sxo',
    appId: '1:257110797951:web:c147b405371afaaeccd94a',
    messagingSenderId: '257110797951',
    projectId: 'seito-flutter-ai-app',
    authDomain: 'seito-flutter-ai-app.firebaseapp.com',
    storageBucket: 'seito-flutter-ai-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPg_fef34UhPpu3b96bCmne7y6Y0unJZM',
    appId: '1:257110797951:android:11d65ca5916adfe2ccd94a',
    messagingSenderId: '257110797951',
    projectId: 'seito-flutter-ai-app',
    storageBucket: 'seito-flutter-ai-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv_N0J_Ee4diGedgVSyWrUjHw13AFOksM',
    appId: '1:257110797951:ios:2b8e3258f0401c6fccd94a',
    messagingSenderId: '257110797951',
    projectId: 'seito-flutter-ai-app',
    storageBucket: 'seito-flutter-ai-app.appspot.com',
    iosBundleId: 'com.example.flutterAiApp',
  );
}
